services:
  operator:
    image: ghcr.io/karak-network/kuda-operator:latest
    environment:
      - AGGREGATOR_URL=
      - KUDA_RPC_URL=
      - KUDA_CONTRACT_ADDRESS=0x0e64c3c675dae7537A9fC1E925E2a87e164f7f53
      - CORE_CONTRACT_ADDRESS=0xb3E2dA61df98E44457190383e1FF13e1ea13280b
      - CELESTIA_RPC_URL=
      - CELESTIA_AUTH_TOKEN=
      - KMS=
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_OPERATOR_KEY_ID=
      - AWS_EIP4844_KEY_ID=
      - OPERATOR_KEYSTORE_PATH=/keystore
      - OPERATOR_KEYSTORE_PASSWORD=
      - EIP4844_KEYSTORE_PATH=/keystore
      - EIP4844_KEYSTORE_PASSWORD=
      - EIP4844_TO_ADDRESS=
      - EIP4844_RPC_URL=
      - EIP4844_BEACON_URL=
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - RUST_LOG=info
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /path/to/keystore:/keystore

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - operator

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
      - 4318:4318
