version: '3'

services:
  operator:
    image: ghcr.io/karak-network/kuda-operator:latest
    environment:
      - AGGREGATOR_URL=
      - KUDA_RPC_URL=
      - KUDA_CONTRACT_ADDRESS=0x03Fe1aaDfc42DF23947A922aA924caCDfa16832b
      - CORE_CONTRACT_ADDRESS=0xb3E2dA61df98E44457190383e1FF13e1ea13280b
      - CELESTIA_RPC_URL=
      - CELESTIA_AUTH_TOKEN=
      - SIGNER_TYPE=
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_OPERATOR_KEY_ID=
      - AWS_EIP4844_KEY_ID=
      - OPERATOR_KEYSTORE_PATH=keystore
      - OPERATOR_KEYSTORE_PASSWORD=
      - OPERATOR_PRIVATE_KEY=
      - EIP4844_KEYSTORE_PATH=keystore
      - EIP4844_KEYSTORE_PASSWORD=
      - EIP4844_PRIVATE_KEY=
      - EIP4844_TO_ADDRESS=
      - EIP4844_RPC_URL=
      - EIP4844_BEACON_URL=
      - RUST_LOG=info
    ports:
      - "8080:8080"
    volumes:
      - {keystore/local/path}:keystore