[workspace]
members = ["cargo:."]

# Config for 'cargo dist'
[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.23.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "~/.karak/bin"
# Whether to install an updater program
install-updater = false
# Where to host releases
hosting = "github"
# Whether to enable GitHub Attestations
github-attestations = true
# Which actions to run on pull requests
pr-run-mode = "upload"

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-latest"
aarch64-unknown-linux-gnu = "buildjet-2vcpu-ubuntu-2204-arm"
x86_64-unknown-linux-gnu = "ubuntu-latest"

[dist.dependencies.homebrew]
protobuf = { version = '*', targets = ["aarch64-apple-darwin"] }

[dist.dependencies.apt]
protobuf-compiler = { version = '*', targets = [
    "aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu",
] }
