name: Build and release operator binaries

on:
  push:
    branches: ["johanan/release-ci"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  VERSION: ${{ github.ref_name }}

jobs:
  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x86_64
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            name: kuda-operator-linux-x86_64
            cross: false
          - build: linux-aarch64
            os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
            cross: true
            name: kuda-operator-linux-aarch64
          - build: macos-aarch64
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            name: kuda-operator-macos-aarch64
            cross: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup | Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Install packages (Linux x86_64)
        if: matrix.build == 'linux-x86_64'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install cross toolchain (Linux aarch64)
        if: matrix.build == 'linux-aarch64'
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: aarch64-unknown-linux-gnu

      - name: Install packages (MacOS aarch64)
        if: matrix.build == 'macos-aarch64'
        shell: bash
        run: |
          brew update && brew install protobuf

      - name: Build | Cargo build
        if: matrix.cross == false
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build | Cross build
        if: matrix.cross == true
        run: cross build --release --target ${{ matrix.target }}

      - name: Post Build | Prepare artifacts
        run: |
          mkdir ${{ matrix.name }}
          cp target/${{ matrix.target }}/release/kuda-operator ${{ matrix.name }}
          cp target/${{ matrix.target }}/release/kuda-operator-register ${{ matrix.name }}
          tar czvf ${{ matrix.name }}.tar.gz ${{ matrix.name }}
          shasum -a 256 ${{ matrix.name }}.tar.gz > ${{ matrix.name }}.sha256
